project_id = "dnyjlmtiliqkpxwsgqyn"

[storage]
file_size_limit = "250MB"

[functions.process-email-queue]
verify_jwt = true

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.send-gmail-email]
verify_jwt = false

[functions.verify-nevorai-member]
verify_jwt = false

[functions.confirm-nevorai-otp]
verify_jwt = false

[functions.check-funnel-view-limit]
verify_jwt = false

