/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingPagesIndexRouteImport } from './routes/landing-pages.index'
import { Route as FunnelsIndexRouteImport } from './routes/funnels.index'
import { Route as VIdRouteImport } from './routes/v.$id'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as LandingPagesCreateRouteImport } from './routes/landing-pages.create'
import { Route as LandingPagesIdRouteImport } from './routes/landing-pages.$id'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as FunnelsCreateRouteImport } from './routes/funnels.create'
import { Route as FunnelsIdRouteImport } from './routes/funnels.$id'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as LandingPagesIdEditRouteImport } from './routes/landing-pages.$id.edit'
import { Route as FunnelsIdEditRouteImport } from './routes/funnels.$id.edit'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/videos.lazy').then((d) => d.Route))
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/live.lazy').then((d) => d.Route))
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/leads.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LandingPagesIndexRoute = LandingPagesIndexRouteImport.update({
  id: '/landing-pages/',
  path: '/landing-pages/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/landing-pages.index.lazy').then((d) => d.Route),
)
const FunnelsIndexRoute = FunnelsIndexRouteImport.update({
  id: '/funnels/',
  path: '/funnels/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/funnels.index.lazy').then((d) => d.Route))
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/v.$id.lazy').then((d) => d.Route))
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s.$slug.lazy').then((d) => d.Route))
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LiveRoute,
} as any).lazy(() => import('./routes/live.$id.lazy').then((d) => d.Route))
const LandingPagesCreateRoute = LandingPagesCreateRouteImport.update({
  id: '/landing-pages/create',
  path: '/landing-pages/create',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/landing-pages.create.lazy').then((d) => d.Route),
)
const LandingPagesIdRoute = LandingPagesIdRouteImport.update({
  id: '/landing-pages/$id',
  path: '/landing-pages/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/landing-pages.$id.lazy').then((d) => d.Route),
)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/l.$slug.lazy').then((d) => d.Route))
const FunnelsCreateRoute = FunnelsCreateRouteImport.update({
  id: '/funnels/create',
  path: '/funnels/create',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/funnels.create.lazy').then((d) => d.Route),
)
const FunnelsIdRoute = FunnelsIdRouteImport.update({
  id: '/funnels/$id',
  path: '/funnels/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/funnels.$id.lazy').then((d) => d.Route))
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/f.$slug.lazy').then((d) => d.Route))
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.whatsapp.lazy').then((d) => d.Route),
)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.videos.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.users.lazy').then((d) => d.Route))
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.support.lazy').then((d) => d.Route))
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.subscriptions.lazy').then((d) => d.Route),
)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.settings.lazy').then((d) => d.Route),
)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.kyc.lazy').then((d) => d.Route))
const LandingPagesIdEditRoute = LandingPagesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LandingPagesIdRoute,
} as any).lazy(() =>
  import('./routes/landing-pages.$id.edit.lazy').then((d) => d.Route),
)
const FunnelsIdEditRoute = FunnelsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FunnelsIdRoute,
} as any).lazy(() =>
  import('./routes/funnels.$id.edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/live': typeof LiveRouteWithChildren
  '/videos': typeof VideosRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/f/$slug': typeof FSlugRoute
  '/funnels/$id': typeof FunnelsIdRouteWithChildren
  '/funnels/create': typeof FunnelsCreateRoute
  '/l/$slug': typeof LSlugRoute
  '/landing-pages/$id': typeof LandingPagesIdRouteWithChildren
  '/landing-pages/create': typeof LandingPagesCreateRoute
  '/live/$id': typeof LiveIdRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$id': typeof VIdRoute
  '/funnels/': typeof FunnelsIndexRoute
  '/landing-pages/': typeof LandingPagesIndexRoute
  '/funnels/$id/edit': typeof FunnelsIdEditRoute
  '/landing-pages/$id/edit': typeof LandingPagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/live': typeof LiveRouteWithChildren
  '/videos': typeof VideosRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/f/$slug': typeof FSlugRoute
  '/funnels/$id': typeof FunnelsIdRouteWithChildren
  '/funnels/create': typeof FunnelsCreateRoute
  '/l/$slug': typeof LSlugRoute
  '/landing-pages/$id': typeof LandingPagesIdRouteWithChildren
  '/landing-pages/create': typeof LandingPagesCreateRoute
  '/live/$id': typeof LiveIdRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$id': typeof VIdRoute
  '/funnels': typeof FunnelsIndexRoute
  '/landing-pages': typeof LandingPagesIndexRoute
  '/funnels/$id/edit': typeof FunnelsIdEditRoute
  '/landing-pages/$id/edit': typeof LandingPagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/live': typeof LiveRouteWithChildren
  '/videos': typeof VideosRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/f/$slug': typeof FSlugRoute
  '/funnels/$id': typeof FunnelsIdRouteWithChildren
  '/funnels/create': typeof FunnelsCreateRoute
  '/l/$slug': typeof LSlugRoute
  '/landing-pages/$id': typeof LandingPagesIdRouteWithChildren
  '/landing-pages/create': typeof LandingPagesCreateRoute
  '/live/$id': typeof LiveIdRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$id': typeof VIdRoute
  '/funnels/': typeof FunnelsIndexRoute
  '/landing-pages/': typeof LandingPagesIndexRoute
  '/funnels/$id/edit': typeof FunnelsIdEditRoute
  '/landing-pages/$id/edit': typeof LandingPagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/live'
    | '/videos'
    | '/admin/kyc'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/whatsapp'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/f/$slug'
    | '/funnels/$id'
    | '/funnels/create'
    | '/l/$slug'
    | '/landing-pages/$id'
    | '/landing-pages/create'
    | '/live/$id'
    | '/s/$slug'
    | '/v/$id'
    | '/funnels/'
    | '/landing-pages/'
    | '/funnels/$id/edit'
    | '/landing-pages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/live'
    | '/videos'
    | '/admin/kyc'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/whatsapp'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/f/$slug'
    | '/funnels/$id'
    | '/funnels/create'
    | '/l/$slug'
    | '/landing-pages/$id'
    | '/landing-pages/create'
    | '/live/$id'
    | '/s/$slug'
    | '/v/$id'
    | '/funnels'
    | '/landing-pages'
    | '/funnels/$id/edit'
    | '/landing-pages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/live'
    | '/videos'
    | '/admin/kyc'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/whatsapp'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/f/$slug'
    | '/funnels/$id'
    | '/funnels/create'
    | '/l/$slug'
    | '/landing-pages/$id'
    | '/landing-pages/create'
    | '/live/$id'
    | '/s/$slug'
    | '/v/$id'
    | '/funnels/'
    | '/landing-pages/'
    | '/funnels/$id/edit'
    | '/landing-pages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  LiveRoute: typeof LiveRouteWithChildren
  VideosRoute: typeof VideosRoute
  FSlugRoute: typeof FSlugRoute
  FunnelsIdRoute: typeof FunnelsIdRouteWithChildren
  FunnelsCreateRoute: typeof FunnelsCreateRoute
  LSlugRoute: typeof LSlugRoute
  LandingPagesIdRoute: typeof LandingPagesIdRouteWithChildren
  LandingPagesCreateRoute: typeof LandingPagesCreateRoute
  SSlugRoute: typeof SSlugRoute
  VIdRoute: typeof VIdRoute
  FunnelsIndexRoute: typeof FunnelsIndexRoute
  LandingPagesIndexRoute: typeof LandingPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages/': {
      id: '/landing-pages/'
      path: '/landing-pages'
      fullPath: '/landing-pages/'
      preLoaderRoute: typeof LandingPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels/': {
      id: '/funnels/'
      path: '/funnels'
      fullPath: '/funnels/'
      preLoaderRoute: typeof FunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/landing-pages/create': {
      id: '/landing-pages/create'
      path: '/landing-pages/create'
      fullPath: '/landing-pages/create'
      preLoaderRoute: typeof LandingPagesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages/$id': {
      id: '/landing-pages/$id'
      path: '/landing-pages/$id'
      fullPath: '/landing-pages/$id'
      preLoaderRoute: typeof LandingPagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels/create': {
      id: '/funnels/create'
      path: '/funnels/create'
      fullPath: '/funnels/create'
      preLoaderRoute: typeof FunnelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels/$id': {
      id: '/funnels/$id'
      path: '/funnels/$id'
      fullPath: '/funnels/$id'
      preLoaderRoute: typeof FunnelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/landing-pages/$id/edit': {
      id: '/landing-pages/$id/edit'
      path: '/edit'
      fullPath: '/landing-pages/$id/edit'
      preLoaderRoute: typeof LandingPagesIdEditRouteImport
      parentRoute: typeof LandingPagesIdRoute
    }
    '/funnels/$id/edit': {
      id: '/funnels/$id/edit'
      path: '/edit'
      fullPath: '/funnels/$id/edit'
      preLoaderRoute: typeof FunnelsIdEditRouteImport
      parentRoute: typeof FunnelsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LiveRouteChildren {
  LiveIdRoute: typeof LiveIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveIdRoute: LiveIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface FunnelsIdRouteChildren {
  FunnelsIdEditRoute: typeof FunnelsIdEditRoute
}

const FunnelsIdRouteChildren: FunnelsIdRouteChildren = {
  FunnelsIdEditRoute: FunnelsIdEditRoute,
}

const FunnelsIdRouteWithChildren = FunnelsIdRoute._addFileChildren(
  FunnelsIdRouteChildren,
)

interface LandingPagesIdRouteChildren {
  LandingPagesIdEditRoute: typeof LandingPagesIdEditRoute
}

const LandingPagesIdRouteChildren: LandingPagesIdRouteChildren = {
  LandingPagesIdEditRoute: LandingPagesIdEditRoute,
}

const LandingPagesIdRouteWithChildren = LandingPagesIdRoute._addFileChildren(
  LandingPagesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  LiveRoute: LiveRouteWithChildren,
  VideosRoute: VideosRoute,
  FSlugRoute: FSlugRoute,
  FunnelsIdRoute: FunnelsIdRouteWithChildren,
  FunnelsCreateRoute: FunnelsCreateRoute,
  LSlugRoute: LSlugRoute,
  LandingPagesIdRoute: LandingPagesIdRouteWithChildren,
  LandingPagesCreateRoute: LandingPagesCreateRoute,
  SSlugRoute: SSlugRoute,
  VIdRoute: VIdRoute,
  FunnelsIndexRoute: FunnelsIndexRoute,
  LandingPagesIndexRoute: LandingPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
